config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :shops, only: [:index, :show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :shop_employees
  has_many :shops, through: :shop_employees
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :shop

  validates_presence_of :animal_type, :age
  validates_numericality_of :age
  
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :pets
  has_many :shop_employees
  has_many :employees, through: :shop_employees

  def self.total_pets
    Shop.joins(:pets).count(:id)
  end
end

app/models/shop_employee.rb
class ShopEmployee < ApplicationRecord
  belongs_to :shop
  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.create(shop_name: params[:shop][:shop_name], city: params[:shop][:city])
    if @shop.save
      redirect_to shops_path
    else
      render :new
    end
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy
    redirect_to shops_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/index.html.erb
<h1>Find a Pet Shop!</h1>
<% @shops.each do |shop| %>
<%= link_to "#{shop.shop_name}", shop_path(shop.id) %>
<%= shop.city %>

<% end %>
<%= link_to "Add a Shop", new_shop_path %>

app/views/shops/new.html.erb
<h1>Add a Shop</h1>
<%= form_for(@shop) do |f| %>
<%= f.label :shop_name %>
<%= f.text_field :shop_name %>
<%= f.label :city %>
<%= f.text_field :city %>
<%= f.submit %>
<% end %>

app/views/shops/show.html.erb
<h1> <%= @shop.shop_name %> </h1>
<%= @shop.city %>
<%= link_to "Delete Shop", shop_path(@shop), method: :delete %>